<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login_page</name>
   <tag></tag>
   <elementGuidId>2d77afb0-d123-4c80-8b72-c44aca1129a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.StyledButton-sc-2tixpb.hxahma.eds-header__btn.ant-btn-primary.ant-btn-background-ghost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7794508-cc02-4905-a33e-f4a316193829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>909bbe8c-a3b4-4c48-86d1-10e18828be84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn StyledButton-sc-2tixpb hxahma eds-header__btn ant-btn-primary ant-btn-background-ghost</value>
      <webElementGuid>9595c8f8-31f4-45e4-8eda-ff0c95d3fd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>dc0fc551-8b9b-4f75-9906-a52664010916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bdVaJa bCGXIL&quot;]/header[@class=&quot;ant-layout-header eds-header eds-header-landing&quot;]/div[@class=&quot;eds-header__contain eds-header__desktop&quot;]/div[@class=&quot;eds-header__right eds-header--flex&quot;]/button[@class=&quot;ant-btn StyledButton-sc-2tixpb hxahma eds-header__btn ant-btn-primary ant-btn-background-ghost&quot;]</value>
      <webElementGuid>68a5caac-24c8-48d8-a9c5-6bc8f5a74191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>61e30f47-70ee-438a-aad9-e6ca32d1c609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div[2]/button[2]</value>
      <webElementGuid>93051125-168e-4ada-98ea-61110b83282d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::button[1]</value>
      <webElementGuid>bae8bebb-8e88-4c8e-9573-c0c79c26d05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDIA'])[1]/following::button[2]</value>
      <webElementGuid>0610eb30-e950-49fd-9c8d-b178277a8f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>edd71343-3c49-4f61-9ee4-4897de455974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>66b382d0-180b-42b5-b24d-0961fe5e2b6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
