<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>975610f9-1aab-4474-9483-ae5821eeecf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.StyledButton-sc-2tixpb.hxahma.ant-btn-primary.ant-btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>156271aa-66e1-4b4e-bfc1-7922723b33df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d7e08c4-4e5e-472f-a8f7-1222a6a161f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn StyledButton-sc-2tixpb hxahma ant-btn-primary ant-btn-block</value>
      <webElementGuid>3b386790-8432-483b-8463-6d7400957b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>9c60140f-3dfe-406a-9992-8e130592ef07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bxivhb esqsio&quot;]/div[@class=&quot;gst-jumbotron-v2 bg-home-v2-3 gst-container-auth&quot;]/div[@class=&quot;react-reveal gst-container__section&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24 ant-col-lg-10&quot;]/div[@class=&quot;gst-auth-eds&quot;]/div[@class=&quot;ant-row ant-row-middle SRow-sc-jpo9rp czTDaa&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;Wrapper-sc-6qqu0z chfPAn eds-wrapper&quot;]/div[@class=&quot;Content-sc-apgxyy cbbSPv&quot;]/form[@class=&quot;content__body&quot;]/button[@class=&quot;ant-btn StyledButton-sc-2tixpb hxahma ant-btn-primary ant-btn-block&quot;]</value>
      <webElementGuid>1ff8007c-8389-4cbd-aab3-5cc5ba7fb3c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>fad4b26a-5dba-4ad3-9ca7-1851cd9e8c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div/div/div/div/div/form/button</value>
      <webElementGuid>7c47c746-e51d-4087-afe9-aafd5d81a40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/following::button[1]</value>
      <webElementGuid>c82e4b7a-2c1e-4a4a-b42f-365115159f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember Me'])[1]/following::button[2]</value>
      <webElementGuid>5b0378ea-abca-4b7a-a161-7c21a8b8829c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>c10141eb-6a17-47c7-909e-f3759ffab1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>d8b62ef7-8085-4566-83bd-2e55d8efe95a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
