<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This field is required</name>
   <tag></tag>
   <elementGuidId>5fa6de38-ba94-426a-af00-535e7658eef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-invalid-feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>020837e2-b098-47cf-a3b3-98893c7165a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-invalid-feedback</value>
      <webElementGuid>3039bc1f-7a5d-4a2a-8739-2a7c499c4d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required*</value>
      <webElementGuid>a78ccc28-3342-493d-95fa-d364939f73ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container auth__cont auth__cont--reset-password-email&quot;]/div[1]/form[@class=&quot;auth__form&quot;]/div[@class=&quot;form-group c-input-group&quot;]/div[@class=&quot;form-invalid-feedback&quot;]</value>
      <webElementGuid>44d67884-1009-4129-b0cc-aad8c1f8a7d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div</value>
      <webElementGuid>63b40234-b240-4c43-aa1e-c9e853e23cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the E-mail address you use to sign in to'])[1]/following::div[2]</value>
      <webElementGuid>b0f3d42d-7f3d-466d-9900-057548046ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[6]</value>
      <webElementGuid>73fcf166-f0b5-4f79-984d-287e530f16b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send My Password'])[1]/preceding::div[1]</value>
      <webElementGuid>89c3a073-ffaf-4fe1-8af8-a6bad37273a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::div[4]</value>
      <webElementGuid>94176106-91ca-4696-9da9-21be89b599b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This field is required*']/parent::*</value>
      <webElementGuid>e698a4ff-9dd5-4ba9-8b9b-0a297a0e4680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>d10f39f0-4747-4e5a-8224-6c563af85c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This field is required*' or . = 'This field is required*')]</value>
      <webElementGuid>73ee6815-a793-48fe-89e9-011f21f64c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
